# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safesh < Formula
  desc "Drop-in safer replacement for bash in curl|bash flows."
  homepage "https://safesh.sh"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/safesh/safesh/releases/download/v0.2.0/safesh_darwin_amd64.tar.gz"
      sha256 "56c700f7781d712cfd077f728b21a5b99e86c799b9b6e8e12955681896bcc520"

      define_method(:install) do
        bin.install "safesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/safesh/safesh/releases/download/v0.2.0/safesh_darwin_arm64.tar.gz"
      sha256 "59401bbc010d5280e26fa1567daaab5cdabf0f7ee394fb22ad12b98ed0656a51"

      define_method(:install) do
        bin.install "safesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/safesh/safesh/releases/download/v0.2.0/safesh_linux_amd64.tar.gz"
      sha256 "3aeda6dd9a6933f7e1403c1093f34a9bc59c7315bfe7aedf46a8753a2f134198"
      define_method(:install) do
        bin.install "safesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/safesh/safesh/releases/download/v0.2.0/safesh_linux_arm64.tar.gz"
      sha256 "774e0c7cdfc41d84e895b01bb8a1e402b1799055e4a6e18a22b0babf6600bff4"
      define_method(:install) do
        bin.install "safesh"
      end
    end
  end

  test do
    system "#{bin}/safesh", "version"
  end
end
