# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safesh < Formula
  desc "Drop-in safer replacement for bash in curl|bash flows."
  homepage "https://safesh.sh"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/safesh/safesh/releases/download/v1.0.0/safesh_darwin_amd64.tar.gz"
      sha256 "4067fffe1e2f2c0ba28689314c2e3444e9735cd15eb89715b72c0768affb7228"

      define_method(:install) do
        bin.install "safesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/safesh/safesh/releases/download/v1.0.0/safesh_darwin_arm64.tar.gz"
      sha256 "94db70139384dd8ff52e207c707d4a886cc63d5823f5d034e4a34e105a9e0fcf"

      define_method(:install) do
        bin.install "safesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/safesh/safesh/releases/download/v1.0.0/safesh_linux_amd64.tar.gz"
      sha256 "b61d76577e5c9acccaf6c6db867e3faef6ab914800bc29ff70b4d9e5020cd99c"
      define_method(:install) do
        bin.install "safesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/safesh/safesh/releases/download/v1.0.0/safesh_linux_arm64.tar.gz"
      sha256 "7d62927576442cd5259f64449092a40dd13616079c4e6f12948e5abdaea7b664"
      define_method(:install) do
        bin.install "safesh"
      end
    end
  end

  test do
    system "#{bin}/safesh", "version"
  end
end
